# Generated by Django 5.0.1 on 2025-05-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_sharedfile_access_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborationsession',
            old_name='created_by',
            new_name='started_by',
        ),
        migrations.AddField(
            model_name='collaborationparticipant',
            name='cursor_position',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborationparticipant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collaborationsession',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
