# Generated by Django 5.0.1 on 2025-05-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_rename_created_by_collaborationsession_started_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationparticipant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
