# Generated by Django 5.0.1 on 2025-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20250514_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this share expires (optional)', null=True),
        ),
        migrations.AddField(
            model_name='sharedfolder',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this share expires (optional)', null=True),
        ),
    ]
