# Generated by Django 5.0.1 on 2025-05-14 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0008_sharedfile_expires_at_sharedfolder_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('share', 'Share'), ('unshare', 'Unshare'), ('download', 'Download'), ('upload', 'Upload'), ('collaborate', 'Collaborate'), ('admin', 'Admin Action'), ('security', 'Security Event')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('object_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='files_audit_action_657751_idx'), models.Index(fields=['timestamp'], name='files_audit_timesta_0e0bc3_idx'), models.Index(fields=['user'], name='files_audit_user_id_e7f986_idx')],
            },
        ),
    ]
